firstPRMergeComment: >
<<<<<<< HEAD
  Thank you for contributing to ReVanced. Join us on [Discord](https://revanced.app/discord) to receive a role for your contribution.
=======
  Thank you for contributing to ReVanced. Join us on [Discord](https://revanced.app/discord) if you want to receive a contributor role.
>>>>>>> 42b25fedf9895eb15475b1f0345ebe42c4a56b70
