name: Open a PR to main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
<<<<<<< HEAD:.github/workflows/open_pull_request.yml
  MESSAGE: Merge branch `${{ github.head_ref || github.ref_name }}` to `main`
=======
  MESSAGE: merge branch `${{ github.head_ref || github.ref_name }}` to `main`
>>>>>>> 42b25fedf9895eb15475b1f0345ebe42c4a56b70:.github/workflows/pull_request.yml

jobs:
  pull-request:
    name: Open pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Open pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: main
          pr_title: 'chore: ${{ env.MESSAGE }}'
          pr_body: |
            This pull request will ${{ env.MESSAGE }}.
<<<<<<< HEAD:.github/workflows/open_pull_request.yml

=======
          
            ## Dependencies before merge

            - [ ] https://github.com/revanced/revanced-integrations
>>>>>>> 42b25fedf9895eb15475b1f0345ebe42c4a56b70:.github/workflows/pull_request.yml
          pr_draft: true
